"""Renderer smoke tests: the HTML audit report and the terminal output.

test_formats.py covers the machine formats (JSON/SARIF) and
test_report_card.py covers the registry card; this file covers the two
remaining user-facing renderers -- the terminal output a first-time user
sees from `audit`, and the self-contained HTML report it writes -- against
the demo fixtures.
"""
from __future__ import annotations

from pathlib import Path

from markupsafe import escape

import evalwarden
from evalwarden.engine import audit
from evalwarden.reporters.html import render_html
from evalwarden.reporters.terminal import render_terminal


def test_terminal_on_leaky_names_verdict_and_every_finding(leaky_dir: Path):
    result = audit(leaky_dir)
    out = render_terminal(result)

    assert out.startswith(f"evalwarden audit: {result.model.eval_id}")
    assert f"Integrity: {result.score} / 100 BLOCKED" in out
    blocked = ", ".join(sorted({f.id for f in result.blocked_by}))
    assert f"claim blocked by: {blocked}" in out
    for finding in result.findings:
        line = (
            f"{finding.id} [{finding.severity.value}|"
            f"confidence:{finding.confidence.value}] {finding.title}"
        )
        assert line in out
    assert "Integrity score is diagnostic, not a certification." in out


def test_terminal_on_hardened_passes_with_no_findings(hardened_dir: Path):
    result = audit(hardened_dir)
    assert result.verdict == "PASS" and result.findings == []

    out = render_terminal(result)
    assert f"Integrity: {result.score} / 100 PASS" in out
    assert "no blocking findings observed under this policy." in out
    assert "claim blocked by" not in out


def test_html_report_on_leaky_shows_verdict_and_finding_titles(leaky_dir: Path):
    result = audit(leaky_dir)
    page = render_html(result)

    assert page.startswith("<!DOCTYPE html>")
    assert f"evalwarden report: {result.model.eval_id}" in page
    assert f"{result.score} / 100" in page
    assert "<strong>BLOCKED</strong>" in page
    for finding in result.findings:
        assert finding.id in page
        # Titles render through Jinja autoescape; compare in escaped form.
        assert str(escape(finding.title)) in page
    assert f"Generated by evalwarden {evalwarden.__version__}" in page
    # Self-contained by design: no scripts, no remote assets.
    assert "<script" not in page
    assert "http://" not in page and "https://" not in page


def test_html_report_on_hardened_passes_with_no_findings(hardened_dir: Path):
    result = audit(hardened_dir)
    page = render_html(result)

    assert "<strong>PASS</strong>" in page
    assert "<h2>No findings</h2>" in page
    assert f"Generated by evalwarden {evalwarden.__version__}" in page
